/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import javax.swing.JPanel;

/**
 *
 * @author raphael
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        pacientejMenu = new javax.swing.JMenu();
        pacientejMenuItem = new javax.swing.JMenuItem();
        medicojMenu = new javax.swing.JMenu();
        medicojMenuItem = new javax.swing.JMenuItem();
        funcionariojMenu = new javax.swing.JMenu();
        funcionariojMenuItem = new javax.swing.JMenuItem();
        conveniojMenu = new javax.swing.JMenu();
        conveniojMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software de Hospital");
        setExtendedState(6);

        jPanel1.setBorder(null);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        pacientejMenu.setText("Paciente");

        pacientejMenuItem.setText("Paciente");
        pacientejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacientejMenuItemActionPerformed(evt);
            }
        });
        pacientejMenu.add(pacientejMenuItem);

        jMenuBar1.add(pacientejMenu);

        medicojMenu.setText("Médico");

        medicojMenuItem.setText("Médico");
        medicojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicojMenuItemActionPerformed(evt);
            }
        });
        medicojMenu.add(medicojMenuItem);

        jMenuBar1.add(medicojMenu);

        funcionariojMenu.setText("Funcionário");

        funcionariojMenuItem.setText("Funcionário");
        funcionariojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariojMenuItemActionPerformed(evt);
            }
        });
        funcionariojMenu.add(funcionariojMenuItem);

        jMenuBar1.add(funcionariojMenu);

        conveniojMenu.setText("Convênio");

        conveniojMenuItem.setText("Convênio");
        conveniojMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conveniojMenuItemActionPerformed(evt);
            }
        });
        conveniojMenu.add(conveniojMenuItem);

        jMenuBar1.add(conveniojMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pacientejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacientejMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new PacienteJPanel());
    }//GEN-LAST:event_pacientejMenuItemActionPerformed

    private void medicojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new MedicoJPanel());
    }//GEN-LAST:event_medicojMenuItemActionPerformed

    private void funcionariojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new FuncionarioJPanel());
    }//GEN-LAST:event_funcionariojMenuItemActionPerformed

    private void conveniojMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conveniojMenuItemActionPerformed
        // TODO add your handling code here:
        setConteudo(new ConvenioJPanel());
    }//GEN-LAST:event_conveniojMenuItemActionPerformed

    
    private void setConteudo(JPanel tela){
        jPanel1.removeAll();
        jPanel1.add(tela);
        jPanel1.setVisible(false);
        jPanel1.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu conveniojMenu;
    private javax.swing.JMenuItem conveniojMenuItem;
    private javax.swing.JMenu funcionariojMenu;
    private javax.swing.JMenuItem funcionariojMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu medicojMenu;
    private javax.swing.JMenuItem medicojMenuItem;
    private javax.swing.JMenu pacientejMenu;
    private javax.swing.JMenuItem pacientejMenuItem;
    // End of variables declaration//GEN-END:variables
}
